name: costa_feedbacks
description: "Aplicativo para coleta de feedbacks do restaurante da CostaFoods."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  csv: ^6.0.0
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  share_plus: ^7.2.1  # Para compartilhar arquivos
  url_launcher: ^6.2.2  # Para abrir gerenciador de arquivos
  #file_picker: ^7.0.1  # Para escolher diretório

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/costa_feedbacks_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/costa_feedbacks_logo_fundo_branco.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/costa_feedbacks_logo_fundo_branco.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  #image: "" # ✅ Remove a imagem da splash nativa
  android: true
  ios: true
